[project]
name = "audio_to_video"
version = "0.1.0"
description = "自动化视频剪辑工具"
requires-python = ">=3.9"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"] 